### ISSUE TITLE
Where i can find the dependencies of this project?

### ISSUE THREAD

**Issue by p4535992** [engswee/com.equalize.xpi.af.modules#11]
Can you tell me where i can find the dependencies (possibly maven) of the import package "com.sap.XXXXXX" ?

**Comment by engswee** [comment]
These are not open-source libraries so they are not available via Maven. Some are available from the NWDS installation, but a couple need to be extracted from the PI system.

Refer following for more details:-
https://blogs.sap.com/2016/01/22/setup-comequalizexpiafmodules-adapter-module-project-in-nwds-easily-using-egit/
