### ISSUE TITLE
XML2JSON Array on rootNode 

### ISSUE THREAD

**Issue by aluferraz** [engswee/com.equalize.xpi.af.modules#13]
Hi There,

Congrats for your project, very helpful !

I couldn't find a way to generate a JSON within an array on the root node, like the sample bellow.
Is there any way to do that ?

`
[
    {
        "effectiveEndDate": "2200-01-01T00:00:00.000-0800",
        "businessUnits": [
            {
                "name": "UN_NEG"
            }
        ],
        "effectiveStartDate": "2014-01-01T00:00:00.000-0800",
        "payeeId": "TesteIntegr2",
        "lastName": "Teste Integracao2 API",
        "preferredLanguage": "en_US",
        "eventCalendar": {
            "name": "CAL_MEN_EV"
        }
    }
]`

**Comment by engswee** [comment]
As it is, no. It always creates a JSONObject at the top level.

Good news is, this is open-source, so you can fork it and make the changes according to your requirement. And of course, would be great if you can contribute it back to this repository. ;)

**Comment by aluferraz** [comment]
Sure, I will implement that and send a pull request in this repo ! Thanks a lot
