### ISSUE TITLE
CPI: Nordic Characters (e.g. 'ä', 'ö') are mangled with DeepPlain2XMLConverter

### ISSUE THREAD

**Issue by kepatron** [engswee/com.equalize.xpi.af.modules#16]
It seems that at least some nordic characters (ä, Ä, ö, Ö) get mangled in DeepPlain2XMLConverter -conversion on CPI.

The scenario is from UTF-8 to UTF-8, so there should be no other sources of charset corruption.

The conversion script is simply;
```
import com.sap.gateway.ip.core.customdev.util.Message
import com.equalize.cpi.converter.FormatConversionBean

def Message processData(Message message) {
	def fcb = new FormatConversionBean(message.exchange, message.getProperties())
	def output = fcb.convert()
	
	message.setBody(output)
	return message
}
```
![GitHub_FCB_Issue_00](https://user-images.githubusercontent.com/6705572/104923165-5a559980-59a4-11eb-9d99-047cbaacbfe2.png)

"Yrjö Kyrölä" converts into "Yrj�� Kyr��l��"

Might be related to issue "_Encoding of umlaut character corrupted during XML to JSON conversion #10_"

**Comment by kepatron** [comment]
![GitHub_FCB_Issue_00](https://user-images.githubusercontent.com/6705572/104922814-ddc2bb00-59a3-11eb-8e22-3adac0336b34.png)

**Comment by kepatron** [comment]
I came up with a little workaround;

![image](https://user-images.githubusercontent.com/6705572/105012977-70686600-5a47-11eb-9d3f-1d13b80cfe35.png)

Script before FCB step:
```
import com.sap.gateway.ip.core.customdev.util.Message;
import java.util.HashMap;
def Message processData(Message message) {
   def body = message.getBody();

   body = body.replace("ä", "^_a")
   .replace("Ä", "^_A")
   .replace("ö", "^_o")
   .replace("Ö", "^_O")
   .replace("å", "!_a")
   .replace("Å", "!_A")
   
   message.setBody(body);

   return message;
}
```

Script after FCB step:
```
import com.sap.gateway.ip.core.customdev.util.Message;
import java.util.HashMap;
def Message processData(Message message) {
   def body = message.getBody(String)

   body = body.replace("^_a", "ä")
   .replace("^_A", "Ä")
   .replace("^_o", "ö")
   .replace("^_O", "Ö")
   .replace("!_a", "å")
   .replace("!_A", "Å")
   
   message.setBody(body);

   return message;
}
```

**Comment by engswee** [comment]
Hi @kepatron, thanks for bring up this issue.

First things first, this repo is for the PI version of FCB. Can you please reopen the issue in the following repo
https://github.com/engswee/equalize-cpi-converter

I had a quick look and yes, it's possible that there's a encoding related bug somewhere. Can you please include a sample of the IFlow together with input payload? It would make it easier to reproduce the issue and troubleshoot it.

**Comment by kepatron** [comment]
Done: https://github.com/engswee/equalize-cpi-converter/issues/8
