### ISSUE TITLE
AttachmentSplitterBean - retrieve file name from Content Disposition

### ISSUE THREAD

**Issue by engswee** [engswee/com.equalize.xpi.af.modules#7]
Add additional functionality to retrieve the attachment file name from the Content Disposition field of the MIME envelope as detailed the link below:-
https://blogs.sap.com/2015/04/13/attachmentsplitterbean-split-attachments-into-child-messages/comment-page-1/#comment-371552

![mime_envelope](https://cloud.githubusercontent.com/assets/7220623/25185327/a7c47f3e-254f-11e7-8154-abffb7b85337.jpg)

**Comment by codebude** [comment]
Hi @engswee - the attached pullrequest should handle Robert's error. But to get sure, it would be nice, if he could test the changes on his machine.

**Comment by engswee** [comment]
Hi @codebude, thanks so much for the quick contribution.

I have reviewed the commits and from a purely static code review I think it needs further changes. Please have a look and let's discuss if you have any further inputs.

**Comment by robwarde** [comment]
@engswee @codebude  working as expected. FYI the consumer is Salesforce. Thanks ever so much...


![2017-04-24_xxxxxxx16-03-36](https://cloud.githubusercontent.com/assets/27857888/25343691/a76aabb0-2907-11e7-96c8-5d5ec6d69293.jpg)

**Comment by codebude** [comment]
@robwarde Nice to hear that and thanks for the feedback :+1:

**Comment by engswee** [comment]
@robwarde , Thanks for the update. That's great to hear!
