### ISSUE TITLE
Issue Cloning Codes

### ISSUE THREAD

**Issue by Arijit946** [engswee/com.equalize.xpi.af.modules#9]
Hi,
I have set sslverify=false under  Preferences > Team > Git > Configuration in my NWDS but while trying to clone the code, I get the error attached
![gitisuue](https://user-images.githubusercontent.com/27831064/45156200-21fdf800-b1fb-11e8-90e4-7284ea9e6e95.JPG)

Any help will be appreciated.

Thanks
Arijit

**Comment by codebude** [comment]
Hi @Arijit946 ,

I have never used the GIT client of the NWDS,  but it looks like a local problem.

Have you tried to check out the source with another client (e.g. official Github client,  Gitkraken,  Sourcetree,  etc.)? 

If that works, just use a third party client to checkout and after that use the Import-->Existing project function of NWDS.

**Comment by engswee** [comment]
Hi @Arijit946 

Can you check if you have just sslverify or http.sslVerify? Please make sure the case is correct too.
![image](https://user-images.githubusercontent.com/7220623/45199681-9d18ea00-b29f-11e8-91bf-79c5b0adab10.png)


If it still does not work, please follow Raffael's suggestion above - there are many free Git clients available.

@codebude - thanks for helping out. Good to know you are still keeping an eye out on this repository!

**Comment by engswee** [comment]
Closing issue as there is no response after 2 weeks.
